repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # You can update this to the latest Ruff version if needed
    rev: v0.4.5
    hooks:
      # Run the linter (check) without automatic fixes
      - id: ruff
      # Run the formatter
      - id: ruff-format
